version: '3.8'
services:
  game-ws:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "9001:9001"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: game
      MYSQL_USER: gameuser
      MYSQL_PASSWORD: gamepass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
