services:
  tester:
    build: ./tests
    depends_on:
      - nginx
      - backend
      - game-ws
      - prometheus
      - grafana
      - node-exporter
      - cadvisor
      - nginx-exporter
      - php-fpm-exporter
    networks:
      - default
      - monitoring
    environment:
      BASE_URL: http://nginx:80
      WS_URL: ws://nginx/ws
      PROM_URL: http://prometheus:9090
      GRAFANA_URL: http://grafana:3000
      GRAFANA_USER: admin
      GRAFANA_PASS: admin
      TIMEOUT_SECS: "8"
      RETRIES: "8"
    volumes:
      - ./tests:/app/tests
      - ./reports:/reports
    command:
      - pytest
      - -q
      - -m
      - "not slow"
      - --maxfail=1
      - --disable-warnings
      - --junitxml=/reports/junit.xml
      - --html=/reports/report.html
      - --self-contained-html
